# Generated by Django 3.1.7 on 2021-03-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
