# Generated by Django 3.1.7 on 2021-03-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_auto_20210304_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='email',
        ),
        migrations.AddField(
            model_name='instructor',
            name='username',
            field=models.EmailField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
