# Generated by Django 3.1.7 on 2021-03-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_auto_20210304_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='username',
            new_name='email',
        ),
    ]
