# Generated by Django 3.1.7 on 2021-03-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0005_auto_20210304_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructoruser',
            name='email',
            field=models.EmailField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='instructoruser',
            name='full_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='instructoruser',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
