# Generated by Django 3.1.7 on 2021-03-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0007_auto_20210304_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='user',
        ),
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='full_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='password',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InstructorUser',
        ),
    ]
