# Generated by Django 3.1.7 on 2021-03-04 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0010_auto_20210304_1419'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
