# Generated by Django 3.1.7 on 2021-03-04 20:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_length', models.IntegerField(default=24)),
                ('number_weeks', models.IntegerField()),
                ('has_distributor', models.BooleanField(default=False)),
                ('has_wholesaler', models.BooleanField(default=False)),
                ('holding_cost', models.IntegerField()),
                ('backlog_cost', models.IntegerField()),
                ('player_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('is_game_active', models.BooleanField(default=True)),
                ('info_sharing', models.BooleanField(default=True)),
                ('info_delay', models.IntegerField()),
                ('demand_id', models.CharField(max_length=5)),
                ('is_default_game', models.BooleanField(default=True)),
                ('starting_inventory', models.IntegerField()),
                ('player_weeks', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
            ],
        ),
    ]
