# Generated by Django 3.1.7 on 2021-03-08 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_length', models.IntegerField(default=24)),
                ('number_weeks', models.IntegerField()),
                ('has_retailer', models.BooleanField(default=True)),
                ('has_wholesaler', models.BooleanField(default=True)),
                ('holding_cost', models.IntegerField()),
                ('backlog_cost', models.IntegerField()),
                ('player_ids', models.CharField(max_length=20)),
                ('is_game_active', models.BooleanField(default=True)),
                ('info_sharing', models.BooleanField(default=True)),
                ('info_delay', models.IntegerField()),
                ('demand_id', models.CharField(max_length=5)),
                ('is_default_game', models.BooleanField(default=True)),
                ('starting_inventory', models.IntegerField()),
                ('player_weeks', models.CharField(blank=True, max_length=20)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
