# Generated by Django 3.1.7 on 2021-03-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='has_distributor',
        ),
        migrations.AddField(
            model_name='game',
            name='has_retailer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='has_wholesaler',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_ids',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_weeks',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
