# Generated by Django 3.1.7 on 2021-03-06 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='instructor',
        ),
    ]
