# Generated by Django 3.1.7 on 2021-03-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210303_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='time_registered',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
