# Generated by Django 3.1.7 on 2021-03-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210304_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='assigned_games',
            field=models.CharField(default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
